lang = "TS"
package_type = "static"

[[links]]
icon = "FaCodeBranch"
internal = true
label = "Open"
link = "https://gingersociety.org/"

[[links]]
icon = "FaCodeBranch"
internal = true
label = "Pull Requests"
link = "https://github.com/ginger-society/ginger-society-website/pulls"

[[links]]
icon = "FaRegPlayCircle"
internal = true
label = "Pipelines"
link = "https://github.com/ginger-society/ginger-society-website/actions"

[[links]]
icon = "FaGithub"
internal = true
label = "Browse Repo"
link = "https://github.com/ginger-society/ginger-society-website"
