[settings]
git_url_prefix = "https://github.com/ginger-society/ginger-society-website"
take_snapshots = false

[version]
channel = "Nightly"
major = 0
minor = 4
patch = 0
revision = 0

[[references]]
file_name = "package.json"
output_type = "String"
variable = "version"
