name: Publish to ginger-society.github.io

on:
  push:
    branches:
      - main  # Change this to your main branch name if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies and build
        run: |
          npm install
          npm run build  # Adjust this command based on your build script

      - name: Configure git
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Clone ginger-society.github.io repository
        uses: actions/checkout@v2
        with:
          repository: ginger-society/ginger-society.github.io
          token: ${{ secrets.REPO_TOKEN }} 

      - name: Copy build to ginger-society.github.io
        run: |
          cp -r ./dist/* ./ginger-society.github.io/
        working-directory: ./ginger-society.github.io

      - name: Commit and push changes to ginger-society.github.io
        run: |
          cd ./ginger-society.github.io/
          git add .
          git commit -m "Update build"
          git push origin main
