name: Publish to ginger-society.github.io

on:
  push:
    branches:
      - main  # Change this to your main branch name if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies and build
        run: |
          npm install
          npm run build  # Adjust this command based on your build script

      - name: Publish to ginger-society.github.io
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.REPO_TOKEN }}
          publish_dir: ./dist  # Adjust this to your build output directory
